server.port=8083
spring.application.name=bff-cajeros
internal.api.key=clave-interna-bancoxyz-2026
atm.pin.esperado=1234

server.ssl.enabled=true
server.ssl.key-store=classpath:bancoxyz-keystore.p12
server.ssl.key-store-password=bancoxyz2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false