server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bancoxyz_core
spring.datasource.username=core_user
spring.datasource.password=core2026
internal.api.key=clave-interna-bancoxyz-2026

spring.flyway.fail-on-missing-locations=true

server.ssl.enabled=true
server.ssl.key-store=classpath:bancoxyz-keystore.p12
server.ssl.key-store-password=bancoxyz2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz