spring.application.name=batch
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bancoxyz
spring.datasource.username=batch_user
spring.datasource.password=postgres18
spring.batch.jdbc.initialize-schema=always